# Arch Linux Configuration Tool
# YAML Configuration File for GitHub
version: "1.0"
description: "Configuration for Arch Linux setup and maintenance"
author: "Arch Config Tool"
last_updated: "2025-01-19"

categories:
  system_maintenance:
    name: "System Maintenance"
    description: "Essential system maintenance and update tasks"
    order: 1
    icon: "🔧"
    tools:
      - name: "System Update"
        description: "Full system update with pacman"
        command: "sudo pacman -Syu --noconfirm"
        tags: ["update", "system", "pacman"]
        
      - name: "Clean Package Cache"
        description: "Remove old cached packages to free disk space"
        command: "sudo pacman -Sc --noconfirm"
        tags: ["cleanup", "cache", "disk-space"]
        
      - name: "Remove Orphans"
        description: "Remove orphaned packages that are no longer needed"
        command: "sudo pacman -Rns $(pacman -Qtdq) --noconfirm || echo 'No orphaned packages found'"
        tags: ["cleanup", "orphans"]
        
      - name: "Update Mirrorlist"
        description: "Optimize package mirrors with reflector for faster downloads"
        command: "sudo reflector --latest 20 --protocol https --sort rate --save /etc/pacman.d/mirrorlist"
        tags: ["mirrors", "optimization", "speed"]
        requires: ["reflector"]
        
      - name: "Clear System Logs"
        description: "Clear old systemd journal logs to free space"
        command: "sudo journalctl --vacuum-time=7d"
        tags: ["cleanup", "logs", "systemd"]

  graphics:
    name: "Graphics Drivers"
    description: "Install and configure graphics drivers for optimal performance"
    order: 2
    icon: "🖥️"
    tools:
      - name: "NVIDIA Open Drivers"
        description: "Open-source NVIDIA drivers (recommended for newer cards)"
        command: "sudo pacman -S --noconfirm nvidia-open nvidia-utils lib32-nvidia-utils"
        tags: ["nvidia", "drivers", "open-source"]
        requires: ["nvidia-hardware"]
        
      - name: "NVIDIA Proprietary"
        description: "Proprietary NVIDIA drivers (for older cards or specific needs)"
        command: "sudo pacman -S --noconfirm nvidia nvidia-utils lib32-nvidia-utils"
        tags: ["nvidia", "drivers", "proprietary"]
        requires: ["nvidia-hardware"]
        
      - name: "AMD Drivers"
        description: "AMD graphics drivers with Vulkan support"
        command: "sudo pacman -S --noconfirm mesa lib32-mesa vulkan-radeon lib32-vulkan-radeon"
        tags: ["amd", "drivers", "mesa", "vulkan"]
        requires: ["amd-hardware"]
        
      - name: "Intel Graphics"
        description: "Intel integrated graphics drivers"
        command: "sudo pacman -S --noconfirm mesa lib32-mesa vulkan-intel lib32-vulkan-intel"
        tags: ["intel", "drivers", "integrated"]
        requires: ["intel-hardware"]

  development:
    name: "Development Tools"
    description: "Essential development and programming tools"
    order: 3
    icon: "💻"
    tools:
      - name: "Git"
        description: "Distributed version control system"
        command: "sudo pacman -S --noconfirm git"
        tags: ["git", "vcs", "development"]
        
      - name: "Base Development"
        description: "Essential development tools (gcc, make, etc.)"
        command: "sudo pacman -S --noconfirm base-devel"
        tags: ["development", "compiler", "build-tools"]
        
      - name: "Visual Studio Code"
        description: "Popular code editor from Microsoft"
        command: "paru -S --noconfirm visual-studio-code-bin"
        tags: ["editor", "ide", "microsoft"]
        requires: ["aur-helper"]
        
      - name: "Docker"
        description: "Container platform for development and deployment"
        command: "sudo pacman -S --noconfirm docker docker-compose && sudo systemctl enable docker"
        tags: ["docker", "containers", "devops"]
        
      - name: "Node.js & NPM"
        description: "JavaScript runtime and package manager"
        command: "sudo pacman -S --noconfirm nodejs npm"
        tags: ["nodejs", "javascript", "npm"]
        
      - name: "Python Development"
        description: "Python interpreter and development tools"
        command: "sudo pacman -S --noconfirm python python-pip python-virtualenv"
        tags: ["python", "pip", "development"]

  multimedia:
    name: "Multimedia"
    description: "Audio, video and multimedia applications"
    order: 4
    icon: "🎵"
    tools:
      - name: "VLC Media Player"
        description: "Versatile multimedia player that plays most formats"
        command: "sudo pacman -S --noconfirm vlc"
        tags: ["video", "audio", "player", "codec"]
        
      - name: "Firefox Browser"
        description: "Open-source web browser from Mozilla"
        command: "sudo pacman -S --noconfirm firefox"
        tags: ["browser", "web", "mozilla"]
        
      - name: "GIMP"
        description: "GNU Image Manipulation Program for photo editing"
        command: "sudo pacman -S --noconfirm gimp"
        tags: ["image", "photo", "editing", "graphics"]
        
      - name: "OBS Studio"
        description: "Open-source streaming and recording software"
        command: "sudo pacman -S --noconfirm obs-studio"
        tags: ["streaming", "recording", "obs", "video"]
        optional: true
        
      - name: "Spotify"
        description: "Music streaming service client"
        command: "paru -S --noconfirm spotify"
        tags: ["music", "streaming", "spotify"]
        requires: ["aur-helper"]
        optional: true

  gaming:
    name: "Gaming"
    description: "Gaming platforms and utilities"
    order: 5
    icon: "🎮"
    tools:
      - name: "Steam"
        description: "Popular gaming platform from Valve"
        command: "sudo pacman -S --noconfirm steam"
        tags: ["gaming", "steam", "valve"]
        
      - name: "Lutris"
        description: "Gaming client for managing games from multiple sources"
        command: "sudo pacman -S --noconfirm lutris"
        tags: ["gaming", "lutris", "wine", "emulation"]
        
      - name: "Wine"
        description: "Windows compatibility layer for running Windows games"
        command: "sudo pacman -S --noconfirm wine winetricks"
        tags: ["wine", "windows", "compatibility"]
        
      - name: "GameMode"
        description: "Optimize system performance for gaming"
        command: "sudo pacman -S --noconfirm gamemode lib32-gamemode"
        tags: ["gaming", "performance", "optimization"]

  productivity:
    name: "Productivity"
    description: "Office applications and productivity tools"
    order: 6
    icon: "📄"
    tools:
      - name: "LibreOffice"
        description: "Complete office suite (Writer, Calc, Impress, etc.)"
        command: "sudo pacman -S --noconfirm libreoffice-fresh"
        tags: ["office", "documents", "spreadsheet", "presentation"]
        
      - name: "Thunderbird"
        description: "Email client from Mozilla"
        command: "sudo pacman -S --noconfirm thunderbird"
        tags: ["email", "client", "mozilla"]
        
      - name: "Discord"
        description: "Communication platform for communities"
        command: "sudo pacman -S --noconfirm discord"
        tags: ["communication", "chat", "voice"]
        
      - name: "Telegram"
        description: "Secure messaging application"
        command: "sudo pacman -S --noconfirm telegram-desktop"
        tags: ["messaging", "secure", "communication"]

  security:
    name: "Security & Privacy"
    description: "Security tools and privacy applications"
    order: 7
    icon: "🔐"
    tools:
      - name: "UFW Firewall"
        description: "Uncomplicated Firewall for basic network protection"
        command: "sudo pacman -S --noconfirm ufw && sudo ufw enable"
        tags: ["firewall", "security", "network"]
        
      - name: "ClamAV Antivirus"
        description: "Open-source antivirus scanner"
        command: "sudo pacman -S --noconfirm clamav && sudo freshclam"
        tags: ["antivirus", "security", "scanner"]
        
      - name: "Tor Browser"
        description: "Anonymous web browser for privacy"
        command: "paru -S --noconfirm tor-browser"
        tags: ["privacy", "anonymity", "browser", "tor"]
        requires: ["aur-helper"]
        
      - name: "KeePassXC"
        description: "Secure password manager"
        command: "sudo pacman -S --noconfirm keepassxc"
        tags: ["password", "security", "encryption"]

  aur_helpers:
    name: "AUR Helpers"
    description: "AUR (Arch User Repository) helper tools"
    order: 8
    icon: "📦"
    tools:
      - name: "Install Yay"
        description: "Yet Another Yaourt - Popular AUR helper written in Go"
        command: "git clone https://aur.archlinux.org/yay.git /tmp/yay && cd /tmp/yay && makepkg -si --noconfirm"
        tags: ["aur", "helper", "yay", "package-manager"]
        requires: ["git", "base-devel"]
        
      - name: "Install Paru"
        description: "Feature-packed AUR helper written in Rust"
        command: "git clone https://aur.archlinux.org/paru.git /tmp/paru && cd /tmp/paru && makepkg -si --noconfirm"
        tags: ["aur", "helper", "paru", "package-manager"]
        requires: ["git", "base-devel"]

  flatpak:
    name: "Flatpak Applications"
    description: "Universal Linux applications via Flatpak"
    order: 9
    icon: "📱"
    tools:
      - name: "Setup Flatpak"
        description: "Install Flatpak and add Flathub repository"
        command: "sudo pacman -S --noconfirm flatpak && flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo"
        tags: ["flatpak", "setup", "flathub"]
        
      - name: "Blender (Flatpak)"
        description: "3D creation suite via Flatpak"
        command: "flatpak install -y flathub org.blender.Blender"
        tags: ["3d", "modeling", "animation", "flatpak"]
        requires: ["flatpak"]
        
      - name: "ONLYOFFICE (Flatpak)"
        description: "Modern office suite with Microsoft Office compatibility"
        command: "flatpak install -y flathub org.onlyoffice.desktopeditors"
        tags: ["office", "documents", "microsoft-compatible", "flatpak"]
        requires: ["flatpak"]
